apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-selfsigned
spec:
  dnsNames:
    - teste.com.br
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
---